### PR TITLE
Testworld coverage for Entity/EntityRelationship

### LINKED ISSUE #959: testworld testcases for Entity/EntityRelationship
# Testworld Entity/ER

- [x] Simple Testcase
  - Create entity, Share ER. Get Entity

- [x] Revocation
    - A: Create,Share w/B
    - B: Get 200
    - A: Revoke ER
    - B: attempt to get again and fail

- [x] Update Entity
    - Alice creates Entity 
    - Alice shares ER with Bob
    - Bob Get Entity
    - Alice updates ER
    - Bob requests new ER version

- [x] Wrong DID 
    - Alice creates entity
    - Alice share ER with Bob
    - Charlie request Alice with Bob ER

- [x] Get All Relationships associated with Entity
    - Alice creates Entity
    - shares with Bob
    - Alice Get Entity 
        - one ER listed
    - Alice shares E with Charlie
        - two ER listed
    - Alice revokes ER Charlie
        - two ER listed (one marked as revoked)

### PR DESCRIPTION
**Pull request by charleenfei**
<This is intended as a guide when describing-reviewing pull requests for go-centrifuge>
Closes #959 .

### CODE REVIEW

File: documents/entity/service.go [hunk 1]
```diff
@@ -210,14 +213,64 @@ func (s service) DeriveEntityResponse(model documents.Model) (*cliententitypb.En
...
+			if err != nil {
+				return nil, err
+			}
+			if len(tokens) != 0 {
+				active = true
+			}
+			targetDID := m.(*entityrelationship.EntityRelationship).TargetIdentity.String()
+			r := &cliententitypb.Relationship{
+				Identity: targetDID,
+				Active:   active,
```
Comment (mikiquantum) [inline documents/entity/service.go]: This can be simplified to: 
```suggestion
				Active:   (len(tokens) != 0),
```

Comment (charleenfei) [reply documents/entity/service.go]: 👍
