### PR TITLE
fix the race condition with config

### LINKED ISSUE #362: race condition with test bootstrapper

### LINKED ISSUE #389: Variadic Race Condition during integration tests
```
[2018-10-30 11:03:18] 2018/10/30 11:02:51 proto: duplicate proto type registered: invoice.InvoiceData
[2018-10-30 11:03:18] 2018/10/30 11:02:51 proto: duplicate proto type registered: purchaseorder.PurchaseOrderData
[2018-10-30 11:03:18] 30.10.2018 11:02:51.436   INFO   config:  Loading user specified config from /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/build/configs/testing_config.yaml configuration.go:248
[2018-10-30 11:03:18] 30.10.2018 11:02:51.439   INFO   storage:  Set storage.Path to: /tmp/centrifuge_data.leveldb_TESTING_31cfbe9fbd967ce2e6f81c06d327840ff48e16cc43e50823c062111dc33c00f8 test_bootstrapper.go:18
[2018-10-30 11:03:18] 30.10.2018 11:02:51.460   INFO   storage:  Setting levelDb at: /tmp/centrifuge_data.leveldb_TESTING_31cfbe9fbd967ce2e6f81c06d327840ff48e16cc43e50823c062111dc33c00f8 test_bootstrapper.go:24
[2018-10-30 11:03:18] 30.10.2018 11:02:51.460   INFO   geth-client:  Opening connection to Ethereum: ws://localhost:9546 geth_client.go:113
[2018-10-30 11:03:18] 30.10.2018 11:02:51.501   INFO   invoice-service:  coredoc received d8c1e8ef4d2d14fed8be3e4838cb3695101a2cd2c6c9f98a94c4fcb3fdc0aaad with signing root b1d363c62039e3103e0975bab38d8d0f7e5066b639c14fb9b7df1236bec1b9d7 service.go:342
[2018-10-30 11:03:18] 30.10.2018 11:02:51.504   INFO   invoice-service:  signed coredoc d8c1e8ef4d2d14fed8be3e4838cb3695101a2cd2c6c9f98a94c4fcb3fdc0aaad with version d8c1e8ef4d2d14fed8be3e4838cb3695101a2cd2c6c9f98a94c4fcb3fdc0aaad service.go:361
[2018-10-30 11:03:18] 30.10.2018 11:02:51.509   INFO   invoice-service:  coredoc received d8c1e8ef4d2d14fed8be3e4838cb3695101a2cd2c6c9f98a94c4fcb3fdc0aaad with signing root b1d363c62039e3103e0975bab38d8d0f7e5066b639c14fb9b7df1236bec1b9d7 service.go:342
[2018-10-30 11:03:18] 30.10.2018 11:02:51.522   INFO   invoice-service:  coredoc received 984890d523c303e6e623a753df41e8399506732e96b8a0d295b68e1ad7b71fa7 with signing root 14fd59740cbed86579a87c5b10fd12cbaae855f6f2629f1c9ba5adc62221403d service.go:342
[2018-10-30 11:03:18] 30.10.2018 11:02:51.524   INFO   invoice-service:  signed coredoc 984890d523c303e6e623a753df41e8399506732e96b8a0d295b68e1ad7b71fa7 with version 984890d523c303e6e623a753df41e8399506732e96b8a0d295b68e1ad7b71fa7 service.go:361
[2018-10-30 11:03:18] 30.10.2018 11:02:51.535   INFO   invoice-service:  coredoc received 984890d523c303e6e623a753df41e8399506732e96b8a0d295b68e1ad7b71fa7 with signing root 1355842248097c0bfe8cd10e835c93aa538fb719da2e48f7b2860eb857a8c268 service.go:342
[2018-10-30 11:03:18] 30.10.2018 11:02:51.538   INFO   invoice-service:  signed coredoc 984890d523c303e6e623a753df41e8399506732e96b8a0d295b68e1ad7b71fa7 with version 3ecefb89b5f4ae7b5041d4da5d14ffcd6f623c68d7a47788383c6da87d19d1ed service.go:361
[2018-10-30 11:03:18] 30.10.2018 11:02:51.550   INFO   invoice-service:  coredoc received 571052176c3e37217d7e93ab7a0d2dac78e6f08e2d66f9d46a188b9e7a10efa9 with signing root 331a0af13dc72d261a88414d69341147f3c123f92eb9af071b908e4ec0d896e1 service.go:342
[2018-10-30 11:03:18] 30.10.2018 11:02:51.552   INFO   invoice-service:  signed coredoc 571052176c3e37217d7e93ab7a0d2dac78e6f08e2d66f9d46a188b9e7a10efa9 with version 571052176c3e37217d7e93ab7a0d2dac78e6f08e2d66f9d46a188b9e7a10efa9 service.go:361
[2018-10-30 11:03:18] 30.10.2018 11:02:51.555   INFO   identity:  Creating Identity [baab63ebbe03] ethereum_identity.go:347
[2018-10-30 11:03:18] 30.10.2018 11:03:02.601   INFO   identity:  Waiting for confirmation for the ID [baab63ebbe03] id_registration_confirmation_task.go:83
[2018-10-30 11:03:18] 30.10.2018 11:03:02.605   INFO   identity:  Sent off identity creation [CentrifugeID [0xbaab63ebbe03]]. Ethereum transaction hash [5a8cd6bd670601e57857154f4c53df6f1ea958a1977405ecddfbc426707437df] and Nonce [34] and Check [true] ethereum_identity.go:270
[2018-10-30 11:03:18] 30.10.2018 11:03:02.605   INFO   identity:  Transfer pending: 0x5a8cd6bd670601e57857154f4c53df6f1ea958a1977405ecddfbc426707437df
[2018-10-30 11:03:18]  ethereum_identity.go:273
[2018-10-30 11:03:18] 30.10.2018 11:03:04.030   INFO   identity:  Received filtered event Id Registration Confirmation for CentrifugeId [0xbaab63ebbe03]
[2018-10-30 11:03:18]  id_registration_confirmation_task.go:104
[2018-10-30 11:03:18] 30.10.2018 11:03:04.063   INFO   identity:  Waiting for confirmation for the Key [7131b7a604e040fc2ec96865a0e4ddfd26a6abafcf3186a059a87ce9f72277b3] key_registration_confirmation_task.go:119
[2018-10-30 11:03:18] 30.10.2018 11:03:04.075   INFO   identity:  Sent off key [2:7131b7a604e040fc2ec96865a0e4ddfd26a6abafcf3186a059a87ce9f72277b3] to add to CentrifugeID [CentrifugeID [0xbaab63ebbe03]]. Ethereum transaction hash [1f9febed84f13a815c24fc11369ead7fce30ca13f2304d63d46272f1a3395e42] ethereum_identity.go:257
[2018-10-30 11:03:18] 30.10.2018 11:03:06.011   INFO   identity:  Received filtered event Key Registration Confirmation for CentrifugeId [0xbaab63ebbe03] and key [7131b7a604e040fc2ec96865a0e4ddfd26a6abafcf3186a059a87ce9f72277b3] with purpose [2]
[2018-10-30 11:03:18]  key_registration_confirmation_task.go:148
[2018-10-30 11:03:18] 30.10.2018 11:03:06.019   INFO   identity:  Waiting for confirmation for the Key [746c4d8464ad40caadc76c2c0b31393c6ae0d6c5000000000000000000000000] key_registration_confirmation_task.go:119
[2018-10-30 11:03:18] 30.10.2018 11:03:06.023   INFO   identity:  Sent off key [3:746c4d8464ad40caadc76c2c0b31393c6ae0d6c5000000000000000000000000] to add to CentrifugeID [CentrifugeID [0xbaab63ebbe03]]. Ethereum transaction hash [a7ec86d3f2d4e94782231bcf5cb26861d77224fb2665c14290e603d158493b8f] ethereum_identity.go:257
[2018-10-30 11:03:18] 30.10.2018 11:03:08.066   INFO   identity:  Received filtered event Key Registration Confirmation for CentrifugeId [0xbaab63ebbe03] and key [746c4d8464ad40caadc76c2c0b31393c6ae0d6c5000000000000000000000000] with purpose [3]
[2018-10-30 11:03:18]  key_registration_confirmation_task.go:148
[2018-10-30 11:03:18] 30.10.2018 11:03:08.078   INFO   anchorRepository:  Waiting for confirmation for the anchorID [fdb59f524b7c1dc2b0fe7f70f3862cfba474dbcc3a8ace2092f00aea9d3311c6] anchor_confirmation_task.go:136
[2018-10-30 11:03:18] 30.10.2018 11:03:08.081   INFO   anchorRepository:  Sent off the anchor [id: fdb59f524b7c1dc2b0fe7f70f3862cfba474dbcc3a8ace2092f00aea9d3311c6, hash: 7344a1137b44f104a3126847107ba5acbdbd9b96e7395b13f3a67a0a6a23060a] to registry. Ethereum transaction hash [2930f7e0b4e3328b4ece6c70c5292e45fa38129727a61c1060e2d7a511733e1c] and Nonce [37] and Check [true] ethereum_anchor_repository.go:138
[2018-10-30 11:03:18] 30.10.2018 11:03:08.082   INFO   anchorRepository:  Transfer pending: 0x2930f7e0b4e3328b4ece6c70c5292e45fa38129727a61c1060e2d7a511733e1c
[2018-10-30 11:03:18]  ethereum_anchor_repository.go:142
[2018-10-30 11:03:18] 30.10.2018 11:03:10.015   INFO   anchorRepository:  Received filtered event Anchor Confirmation for AnchorID [fdb59f524b7c1dc2b0fe7f70f3862cfba474dbcc3a8ace2092f00aea9d3311c6] and CentrifugeId [0xbaab63ebbe03]
[2018-10-30 11:03:18]  anchor_confirmation_task.go:159
[2018-10-30 11:03:18] 30.10.2018 11:03:10.049   INFO   identity:  Creating Identity [2f7bf1ba2487] ethereum_identity.go:347
[2018-10-30 11:03:18] 30.10.2018 11:03:10.053   INFO   identity:  Waiting for confirmation for the ID [2f7bf1ba2487] id_registration_confirmation_task.go:83
[2018-10-30 11:03:18] 30.10.2018 11:03:10.056   INFO   identity:  Sent off identity creation [CentrifugeID [0x2f7bf1ba2487]]. Ethereum transaction hash [6f504f84be27c29bd83df2657b9d2cf6fd0590ca645d96028d5b79b4cc059e41] and Nonce [38] and Check [true] ethereum_identity.go:270
[2018-10-30 11:03:18] 30.10.2018 11:03:10.056   INFO   identity:  Transfer pending: 0x6f504f84be27c29bd83df2657b9d2cf6fd0590ca645d96028d5b79b4cc059e41
[2018-10-30 11:03:18]  ethereum_identity.go:273
[2018-10-30 11:03:18] 30.10.2018 11:03:12.089   INFO   identity:  Received filtered event Id Registration Confirmation for CentrifugeId [0x2f7bf1ba2487]
[2018-10-30 11:03:18]  id_registration_confirmation_task.go:104
[2018-10-30 11:03:18] 30.10.2018 11:03:12.113   INFO   identity:  Waiting for confirmation for the Key [7131b7a604e040fc2ec96865a0e4ddfd26a6abafcf3186a059a87ce9f72277b3] key_registration_confirmation_task.go:119
[2018-10-30 11:03:18] 30.10.2018 11:03:12.117   INFO   identity:  Sent off key [2:7131b7a604e040fc2ec96865a0e4ddfd26a6abafcf3186a059a87ce9f72277b3] to add to CentrifugeID [CentrifugeID [0x2f7bf1ba2487]]. Ethereum transaction hash [c52bc4a4e80ae809b1afacb1288e1bd996d2841bf371387b9691210b71cc6dc7] ethereum_identity.go:257
[2018-10-30 11:03:18] 30.10.2018 11:03:14.055   INFO   identity:  Received filtered event Key Registration Confirmation for CentrifugeId [0x2f7bf1ba2487] and key [7131b7a604e040fc2ec96865a0e4ddfd26a6abafcf3186a059a87ce9f72277b3] with purpose [2]
[2018-10-30 11:03:18]  key_registration_confirmation_task.go:148
[2018-10-30 11:03:18] 30.10.2018 11:03:14.068   INFO   identity:  Waiting for confirmation for the Key [746c4d8464ad40caadc76c2c0b31393c6ae0d6c5000000000000000000000000] key_registration_confirmation_task.go:119
[2018-10-30 11:03:18] 30.10.2018 11:03:14.078   INFO   identity:  Sent off key [3:746c4d8464ad40caadc76c2c0b31393c6ae0d6c5000000000000000000000000] to add to CentrifugeID [CentrifugeID [0x2f7bf1ba2487]]. Ethereum transaction hash [cb4f4c424133dfc0b9278a1a6b281badf0aae09923f5291574ceca7c90f9310d] ethereum_identity.go:257
[2018-10-30 11:03:18] 30.10.2018 11:03:16.014   INFO   identity:  Received filtered event Key Registration Confirmation for CentrifugeId [0x2f7bf1ba2487] and key [746c4d8464ad40caadc76c2c0b31393c6ae0d6c5000000000000000000000000] with purpose [3]
[2018-10-30 11:03:18]  key_registration_confirmation_task.go:148
[2018-10-30 11:03:18] 30.10.2018 11:03:16.036   INFO   invoice-service:  coredoc received a345c30305cd354a0cdb594fc47c46f1e731e948eb520cc79b3f970e45130960 with signing root 5b563e8e18451f79a442d3a5c9543bda8c1df9c58de78ceb8bffb096847cf130 service.go:342
[2018-10-30 11:03:18] 30.10.2018 11:03:16.039   INFO   invoice-service:  signed coredoc a345c30305cd354a0cdb594fc47c46f1e731e948eb520cc79b3f970e45130960 with version a345c30305cd354a0cdb594fc47c46f1e731e948eb520cc79b3f970e45130960 service.go:361
[2018-10-30 11:03:18] 30.10.2018 11:03:16.044   INFO   anchorRepository:  Waiting for confirmation for the anchorID [a345c30305cd354a0cdb594fc47c46f1e731e948eb520cc79b3f970e45130960] anchor_confirmation_task.go:136
[2018-10-30 11:03:18] 30.10.2018 11:03:16.051   INFO   anchorRepository:  Sent off the anchor [id: a345c30305cd354a0cdb594fc47c46f1e731e948eb520cc79b3f970e45130960, hash: 823d34f79c65fe97f6a0e71afc04490e50b94a0076bb30ec38f811d47fdf8e5b] to registry. Ethereum transaction hash [ebfec8030a0d887e02e99ee2f12d485e7fe391b26043cf48af431ecc3bcc2dc2] and Nonce [41] and Check [true] ethereum_anchor_repository.go:138
[2018-10-30 11:03:18] 30.10.2018 11:03:16.051   INFO   anchorRepository:  Transfer pending: 0xebfec8030a0d887e02e99ee2f12d485e7fe391b26043cf48af431ecc3bcc2dc2
[2018-10-30 11:03:18]  ethereum_anchor_repository.go:142
[2018-10-30 11:03:18] 30.10.2018 11:03:18.089   INFO   anchorRepository:  Received filtered event Anchor Confirmation for AnchorID [a345c30305cd354a0cdb594fc47c46f1e731e948eb520cc79b3f970e45130960] and CentrifugeId [0x2f7bf1ba2487]
[2018-10-30 11:03:18]  anchor_confirmation_task.go:159
[2018-10-30 11:03:18] PASS
[2018-10-30 11:03:18] coverage: 76.5% of statements
[2018-10-30 11:03:18] ==================
[2018-10-30 11:03:18] WARNING: DATA RACE
[2018-10-30 11:03:18] Read at 0x000001e60ab0 by goroutine 69:
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/notification.(*WebhookSender).Send()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/notification/notification.go:30 +0x4f
[2018-10-30 11:03:18] 
[2018-10-30 11:03:18] Previous write at 0x000001e60ab0 by main goroutine:
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/config.(*Bootstrapper).TestTearDown()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/config/test_bootstrapper.go:33 +0x3a
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/context/testingbootstrap.TestFunctionalEthereumTearDown()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/context/testingbootstrap/testing_bootstrap.go:47 +0x9e
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/p2p/p2phandler_test.TestMain()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/p2p/p2phandler/handler_integration_test.go:39 +0x4c
[2018-10-30 11:03:18]   fmt.Fscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:143 +0xf5
[2018-10-30 11:03:18]   fmt.Sscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:114 +0xbb
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x16c
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x2b0
[2018-10-30 11:03:18]   fmt.(*ss).doScanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:1193 +0x345
[2018-10-30 11:03:18]   fmt.Fscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:143 +0xf5
[2018-10-30 11:03:18]   fmt.Sscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:114 +0xbb
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x16c
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x2b0
[2018-10-30 11:03:18]   fmt.(*ss).doScanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:1193 +0x345
[2018-10-30 11:03:18]   fmt.Fscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:143 +0xf5
[2018-10-30 11:03:18]   fmt.Sscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:114 +0xbb
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x16c
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x2b0
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db_util.go:52 +0x2e6
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb.openDB()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:130 +0xa4c
[2018-10-30 11:03:18]   fmt.Sscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:114 +0xbb
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x16c
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x2b0
[2018-10-30 11:03:18]   fmt.Sscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:114 +0xbb
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:657 +0x239
[2018-10-30 11:03:18]   fmt.(*ss).doScanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:1193 +0x345
[2018-10-30 11:03:18]   fmt.Fscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:143 +0xf5
[2018-10-30 11:03:18]   fmt.Sscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:114 +0xbb
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x16c
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x2b0
[2018-10-30 11:03:18]   fmt.(*ss).doScanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:1193 +0x345
[2018-10-30 11:03:18]   fmt.Fscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:143 +0xf5
[2018-10-30 11:03:18]   fmt.Sscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:114 +0xbb
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x16c
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x2b0
[2018-10-30 11:03:18]   fmt.(*ss).doScanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:1193 +0x345
[2018-10-30 11:03:18]   fmt.Fscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:143 +0xf5
[2018-10-30 11:03:18]   fmt.Sscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:114 +0xbb
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x16c
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x2b0
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:476 +0xd9
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb.openDB()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:125 +0xa28
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb.Open()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:197 +0x186
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x16c
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x2b0
[2018-10-30 11:03:18]   fmt.(*ss).doScanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:1193 +0x345
[2018-10-30 11:03:18]   fmt.Fscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:143 +0xf5
[2018-10-30 11:03:18]   fmt.Sscanf()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/fmt/scan.go:114 +0xbb
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x16c
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x2b0
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb.(*session).recover.func1()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/session.go:113 +0xc3
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb.(*session).recover()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/session.go:121 +0x1860
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb.Open()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:183 +0xc8
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb.OpenFile()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/vendor/github.com/syndtr/goleveldb/leveldb/db.go:219 +0x9f
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/storage.NewLevelDBStorage()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/storage/leveldb.go:27 +0xc2
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/storage.(*Bootstrapper).TestBootstrap()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/storage/test_bootstrapper.go:19 +0x24f
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/context/testingbootstrap.TestFunctionalEthereumBootstrap()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/context/testingbootstrap/testing_bootstrap.go:38 +0xb6
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/p2p/p2phandler_test.TestMain()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/p2p/p2phandler/handler_integration_test.go:37 +0x2f
[2018-10-30 11:03:18]   main.main()
[2018-10-30 11:03:18]       _testmain.go:102 +0x320
[2018-10-30 11:03:18] 
[2018-10-30 11:03:18] Goroutine 69 (running) created at:
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/documents/invoice.service.ReceiveAnchoredDocument()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/documents/invoice/service.go:391 +0x89b
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/documents/invoice.(*service).ReceiveAnchoredDocument()
[2018-10-30 11:03:18]       <autogenerated>:1 +0xae
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/p2p/p2phandler.(*Handler).SendAnchoredDocument()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/p2p/p2phandler/handler.go:83 +0x37e
[2018-10-30 11:03:18]   github.com/centrifuge/go-centrifuge/p2p/p2phandler_test.TestHandler_SendAnchoredDocument()
[2018-10-30 11:03:18]       /home/travis/gopath/src/github.com/centrifuge/go-centrifuge/p2p/p2phandler/handler_integration_test.go:239 +0x9cb
[2018-10-30 11:03:18]   testing.tRunner()
[2018-10-30 11:03:18]       /home/travis/.gimme/versions/go1.10.4.linux.amd64/src/testing/testing.go:777 +0x16d
[2018-10-30 11:03:18] ==================
[2018-10-30 11:03:18] panic: runtime error: invalid memory address or nil pointer dereference
[2018-10-30 11:03:18] [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xbe8b16]
[2018-10-30 11:03:18] 
[2018-10-30 11:03:18] goroutine 200 [running]:
[2018-10-30 11:03:18] github.com/centrifuge/go-centrifuge/config.(*Configuration).GetReceiveEventNotificationEndpoint(0x0, 0x5e482df1e29ee902, 0x48cf4360b291e37f)
[2018-10-30 11:03:18] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/config/configuration.go:71 +0x46
[2018-10-30 11:03:18] github.com/centrifuge/go-centrifuge/notification.(*WebhookSender).Send(0x2808200, 0xc4201b4e00, 0x0, 0x0, 0x0)
[2018-10-30 11:03:18] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/notification/notification.go:30 +0x60
[2018-10-30 11:03:18] created by github.com/centrifuge/go-centrifuge/documents/invoice.service.ReceiveAnchoredDocument
[2018-10-30 11:03:18] 	/home/travis/gopath/src/github.com/centrifuge/go-centrifuge/documents/invoice/service.go:391 +0x89c
[2018-10-30 11:03:18] FAIL	github.com/centrifuge/go-centrifuge/p2p/p2phandler	26.752s
```

### PR DESCRIPTION
**Pull request by vedhavyas**
Fixes #389 
Fixes #362 

Turns out both the issues were due to `config.Config` variable being accessed at the same time. #389, it is accessed in `notification.Send` and in #362 it is accessed to set Config to nil in `config/test_bootstrapper.go`.

All the tests share a global namespace and since they are run in parallel and each time the `config/test_boostrapper` is run in each test, which is updating `config.Config`, the race condition happens. Added a functions to set and get config with mutex.

### CODE REVIEW

File: coredocument/coredocument_test.go [hunk 1]
```diff
@@ -232,11 +232,11 @@ func TestGetExternalCollaborators_ErrorConfig(t *testing.T) {
 	c := []string{hexutil.Encode(c1), hexutil.Encode(c2)}
 	cd, err := NewWithCollaborators(c)
 	assert.Equal(t, [][]byte{c1, c2}, cd.Collaborators)
-	currentKeyPath, _ := config.Config.GetSigningKeyPair()
+	currentKeyPath, _ := config.Config().GetSigningKeyPair()
 	//Wrong path
-	config.Config.V.Set("keys.signing.publicKey", "./build/resources/signingKey.pub.pem")
+	config.Config().V.Set("keys.signing.publicKey", "./build/resources/signingKey.pub.pem")
```
Comment (mikiquantum) [inline coredocument/coredocument_test.go]: Should we have another wrapper to lock config when an update like this one happens? Meaning:
```
UpdateConfig(key string, value interface{}) {
  configMu.Lock()
  defer configMu.Unlock()
  config.V.Set(key, value)
}
```
What do you think?

Comment (vedhavyas) [reply coredocument/coredocument_test.go]: I assumed `Viper` functions are thread safe. But seems it is not threadsafe. That makes me sad. So yeah, we need to update that

File: config/configuration.go [hunk 2]
```diff
@@ -13,143 +13,213 @@ import (
...
+	defer configMu.Unlock()
+	config = c
+}
+
+// Configuration holds the configuration details for the node
 type Configuration struct {
+	mu         sync.RWMutex
 	configFile string
-	V          *viper.Viper
+	v          *viper.Viper
```
Comment (mikiquantum) [inline config/configuration.go]: Perfect

**Comment by vedhavyas** [comment]
Yeah we can! But I need to check their issues if anyone raised such concerns. If not, I would be super surprised!
